//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VE.SMS.UI {
    
    
    public partial class AccessControlManagement {
        
        /// <summary>
        /// userManagementControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VE.SMS.UI._UserControl.UserManagementControl userManagementControl;
        
        /// <summary>
        /// roleManagementControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VE.SMS.UI._UserControl.RoleManagementControl roleManagementControl;
        
        /// <summary>
        /// userRoleMangementControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VE.SMS.UI._UserControl.UserRoleMangementControl userRoleMangementControl;
        
        /// <summary>
        /// PermissionControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VE.SMS.UI._UserControl.PermissionControl PermissionControl1;
    }
}
