//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VE.SMS.UI {
    
    
    public partial class EndProductList {
        
        /// <summary>
        /// FinishProductControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VE.SMS.UI._UserControl.FinishProductControl FinishProductControl1;
    }
}
